export const DEFAULT_ROW_HEIGHT = 50
export const DEFAULT_COLUMN_WIDTH = 50
export const DEFAULT_GRID_CELL_DIM = 100
export const TITLE_REGEX = /React Virtualized Window Demo App/
export const DEFAULT_ROW_COUNT = 1000
export const DEFAULT_CELL_COUNT = 200
export const DEFAULT_GAP = 20
export const DEFAULT_VARIABLE_GAP = { horizontal: 40, vertical: 10 }
export const DEFAULT_HEIGHT_ARRAY = [50, 100, 50, 150, 50]
export const DEFAULT_WIDTH_ARRAY = [50, 30, 100, 120, 60]
